import { Translations, TranslationSet } from './types';

const enBase: TranslationSet = {
  navAbout: "About",
  navLegacy: "Our Legacy",
  navOffices: "Offices",
  navServices: "Collaborations",
  navServicesOffered: "Services Offered",
  navImpact: "Our Impact",
  navCareers: "Careers",
  navJoinTeam: "Join Our Team",
  navContact: "Contact Us",
  heroTitle: "The world's leading",
  heroHighlight: "AI-powered",
  heroTitleEnd: "data solutions provider",
  heroSubtitle: "Always On, Never Off",
  heroDescription: "We empower organizations to realize the transformative power of AI—bringing big data to life, launching new ways of thinking, learning, and doing for the good of humankind.",
  heroBtnPrimary: "Request a Consultation",
  heroBtnSecondary: "Explore Services",
  heroBtnTertiary: "Lifewood Portal",
  cardGlobalTitle: "Global Reach",
  cardGlobalText: "40+ delivery centers across 30+ countries worldwide",
  cardSpeedTitle: "Speed & Scale",
  cardSpeedText: "56,000+ global resources ready to deploy",
  cardPrecisionTitle: "Precision",
  cardPrecisionText: "50+ languages and dialects supported",
  cardSecurityTitle: "Secure Data",
  cardSecurityText: "ISO 27001 certified & biometric delivery centers",
  cardDialectTitle: "Local Context",
  cardDialectText: "Expert support for 60+ regional dialects",
  cardEsgTitle: "Diverse Talent",
  cardEsgText: "50% female leadership across global operations",
  cardAlwaysOnTitle: "24/7 Continuity",
  cardAlwaysOnText: "Always on, never off—round-the-clock delivery",
  statCenters: "Global Delivery Centers",
  statCountries: "Countries Worldwide",
  statLanguages: "Language Capabilities",
  statResources: "Global Resources",
  featuresTag: "Our Approach",
  featuresTitle: "Bridging East & West Through Innovation",
  featuresDescription: "With headquarters in Malaysia and offices strategically located across continents, we serve as a super-bridge connecting diverse cultures, technologies, and possibilities.",
  feature1Title: "Adaptable & Innovative",
  feature1Text: "We leverage cutting-edge AI technologies including GPT and Gemini to create transformative solutions that evolve with your needs.",
  feature2Title: "Global Collaboration",
  feature2Text: "Connecting local expertise with global AI infrastructure to empower communities and drive inclusive growth worldwide.",
  feature3Title: "Technology-Driven",
  feature3Text: "Proactive deployment of advanced data processing capabilities to solve real-world problems at unprecedented scale and speed.",
  feature4Title: "ESG Committed",
  feature4Text: "Strong emphasis on Environmental, Social, and Governance principles, including employment diversity and community empowerment.",
  feature5Title: "Always Reliable",
  feature5Text: "Always on, never off—delivering consistent, high-quality results for the world's largest organizations, 24/7/365.",
  feature6Title: "Purposeful Impact",
  feature6Text: "Dedicated to fostering positive change across regions, creating opportunities, and enabling sustainable social progress.",
  bgTag: "Our Legacy",
  bgTitle: "The Legacy of the Super-Bridge",
  bgDesc: "Founded in 2005, Lifewood was born from a vision to architect the link between human context and machine intelligence. Over two decades, we have evolved from a specialized data boutique into a global powerhouse.",
  bgPoint1Title: "20 Years of Excellence",
  bgPoint1Text: "Two decades of refining the 'Human-in-the-Loop' methodology to perfection.",
  bgPoint2Title: "Cultural Intelligence",
  bgPoint2Text: "Deep understanding of 60+ dialects, ensuring AI models are culturally nuanced and unbiased.",
  bgPoint3Title: "The Lifewood Standard",
  bgPoint3Text: "Setting the global benchmark for data security with air-gapped centers and biometric protocols.",
  bgYearsBadge: "Years of Strategic AI Data Engineering",
  officesTitle: "Global Strategic Presence",
  officesDesc: "Operating specialized delivery centers and secure business hubs across the world's most vital technology corridors.",
  officesAlwaysOn: "Always On • Never Off • Global Scale",
  officesRealtime: "Real-time delivery active across all timezones",
  officeRegionHeadquarters: "Headquarters",
  officeRegionDeliveryHub: "Delivery Hub",
  officeRegionOperations: "Operations",
  officeRegionStrategicLab: "Strategic Lab",
  officeRegionBusinessOffice: "Business Office",
  officeRegionRegionalHub: "Regional Hub",
  officeDetailsPetalingJaya: "Global strategic hub managing primary AI data pipelines and enterprise partnerships.",
  officeDetailsManila: "Premier delivery center with 5,000+ specialized annotators for multimodal AI models.",
  officeDetailsDavao: "High-security facility focused on sensitive medical data and secure computer vision tasks.",
  officeDetailsCebu: "Strategic expansion hub supporting multilingual support and specialized annotation services.",
  officeDetailsShenzhen: "Technological R&D center integrating edge computing with human-in-the-loop workflows.",
  officeDetailsTokyo: "Localization powerhouse specializing in Japanese dialect nuances and cultural AI alignment.",
  officeDetailsLondon: "EMEA strategic headquarters driving European AI ethics and regulatory compliance.",
  officeDetailsNewYork: "North American client relations and large-scale project architecting for Tier 1 tech firms.",
  officeDetailsTaipei: "Crucial link for Greater China operations, providing linguistic expertise and technical support.",
  servicesTag: "Collaborations",
  servicesTitle: "Our Clients and Partners",
  servicesDescription: "Featured collaborators include Google, Microsoft, Apple, Ancestry, FamilySearch, BYU-Pathway Worldwide, and Moore Foundation.",
  serviceBadge1: "Featured Client",
  serviceTitle1: "Google",
  serviceDesc1: "Global technology partner featured in Lifewood's client and partner showcase.",
  serviceDetail1: "Google appears as one of Lifewood's highlighted collaborators in the Our Clients And Partners section.",
  serviceBadge2: "Featured Client",
  serviceTitle2: "Microsoft",
  serviceDesc2: "Enterprise technology partner highlighted on Lifewood's official client showcase.",
  serviceDetail2: "Microsoft is presented among Lifewood's valued clients and partners on the homepage collaboration segment.",
  serviceBadge3: "Featured Client",
  serviceTitle3: "Apple",
  serviceDesc3: "Global consumer technology brand shown in Lifewood's partner lineup.",
  serviceDetail3: "Apple is displayed in the client logo string within Lifewood's Our Clients And Partners section.",
  serviceBadge4: "Additional Partners",
  serviceTitle4: "Ancestry, FamilySearch, BYU-Pathway, Moore Foundation",
  serviceDesc4: "Additional organizations shown in the Lifewood partner strip.",
  serviceDetail4: "Also featured in Lifewood's client and partner logos: Ancestry, FamilySearch, BYU-Pathway Worldwide, and Moore Foundation.",
  serviceLearnMore: "View Highlights",
  serviceGoBack: "Back to Summary",
  ctaTitle: "Ready to transform your data into intelligence?",
  ctaDescription: "Join the world's leading organizations who trust Lifewood to power their AI initiatives. Let's bring your data to life and create new possibilities together.",
  ctaBtnPrimary: "Get Started Today",
  ctaBtnSecondary: "Schedule a Consultation",
  footerTagline: "We provide global Data Engineering Services to enable AI Solutions. Empowering organizations through innovative AI-powered data solutions.",
  footerCompany: "Company",
  footerAboutUs: "About Us",
  footerOurTeam: "Our Team",
  footerCareers: "Careers",
  footerNews: "News",
  footerServices: "Collaborations",
  footerResources: "Resources",
  footerCaseStudies: "Case Studies",
  footerDocumentation: "Documentation",
  footerSupport: "Support",
  footerPrivacy: "Privacy Policy",
  footerCookie: "Cookie Policy",
  footerTerms: "Terms & Conditions",
  footerCopyright: "Lifewood Data Technology. All Rights Reserved.",
  modalTitle: "Join Our Global Team",
  modalSubtitle: "Be part of the world's leading AI-powered data solutions provider",
  modalBenefitsTitle: "Why Join Lifewood?",
  benefit1: "Global Opportunities",
  benefit2: "Cutting-Edge AI",
  benefit3: "Competitive Pay",
  benefit4: "Career Growth",
  benefit5: "Inclusive Culture",
  benefit6: "Meaningful Impact",
  formSectionPersonal: "Personal Information",
  formSectionPosition: "Position & Experience",
  formSectionDocs: "Documents",
  formFirstName: "First Name",
  formFirstNamePlaceholder: "e.g. John",
  formLastName: "Last Name",
  formLastNamePlaceholder: "e.g. Doe",
  formEmail: "Email Address",
  formEmailPlaceholder: "john.doe@example.com",
  formPhone: "Phone Number",
  formPhonePlaceholder: "012-345-6789",
  formPositionLabel: "Position Applying For",
  formPositionPlaceholder: "Select position",
  formPosAnnotator: "Data Annotator",
  formPosAnalyst: "Data Analyst",
  formPosTrainer: "AI Trainer",
  formPosManager: "Project Manager",
  formPosIntern: "Intern",
  formExpLabel: "Experience Level",
  formExpPlaceholder: "Select experience level",
  formExpEntry: "Entry Level (0-2 years)",
  formExpMid: "Mid Level (3-5 years)",
  formExpSenior: "Senior Level (6+ years)",
  formWorkLocationLabel: "Preferred Office Location",
  formWorkLocationPlaceholder: "Select preferred location",
  formNeedHelp: "Need help?",
  formResumeLabel: "Upload Resume/CV",
  formResumePlaceholder: "Click or drag and drop to upload resume",
  formResumeSub: "PDF, DOC, DOCX (Max 5MB)",
  formBtnCancel: "Cancel",
  formBtnSubmit: "Submit Application",
  formSuccessTitle: "Application Received",
  formSuccess: "Thank you for your application! Our team will review your submission and contact you within 5-7 business days.",
  formSuccessExplore: "Explore More",
  formSuccessBack: "Back to Home",
  formRequired: "required",
  portalBadge: "The Lifewood Portal",
  portalChip: "Portal",
  portalHeroTitle: "The Enterprise AI Delivery Hub.",
  portalHeroDesc: "Transforming raw data silos into production-ready intelligence with 56,000+ specialized global resources.",
  portalExpLabel: "Years Experience",
  portalNationsLabel: "Nations",
  portalTalentLabel: "Global Talent",
  portalPillarsTitle: "Strategic Pillars",
  portalPillar1Title: "Global Scalability",
  portalPillar1Desc: "Managing 56,000+ specialized resources across 30+ countries isn't just about numbers—it's about a synchronized global engine.",
  portalPillar2Title: "Operational Precision",
  portalPillar2Desc: "We utilize Lean Six Sigma methodologies to achieve 99.9% quality benchmarks across every processing stage.",
  portalPillar3Title: "Ethical Data Stewardship",
  portalPillar3Desc: "As a leader in AI data engineering, we set the standard for privacy with biometric security and air-gapped centers.",
  portalAlwaysOnTitle: "Always On.",
  portalAlwaysOnDesc: "Our global centers operate 24/7 across 3 shifts to ensure your project never stops.",
  portalJourneyTitle: "Our Journey.",
  portalJourneyDesc: "From our humble beginnings in 2005 to managing one of the world's largest AI labeling networks.",
  portalLeadershipTitle: "The Human Algorithm.",
  portalCareersTitle: "Join the Global Force.",
  portalCareersDesc: "We are always looking for visionary data scientists, project managers, and operational experts.",
  portalBtnExplore: "Explore Opportunities",
  portalReturnBtn: "Return to Home Page",
  portalNavHome: "Home",
  portalChip: "Portal",
  portalNavOffers: "Services",
  portalNavIndustries: "Industries",
  portalNavProcess: "Our Process",
  portalNavResults: "Results",
  portalNavContact: "Start Your Project With Us",
  portalNavExit: "Exit Portal",
  portalNavEthics: "Data Ethics",
  portalNavPricing: "Pricing",
  portalOffersTitle: "Core Services",
  portalOffersDesc: "High-fidelity data engineering services optimized for enterprise scale.",
  portalProcessTitle: "Engagement Blueprint",
  portalProcessDesc: "How we move from assessment to 24/7 production scale.",
  portalEngagementTitle: "Proven Results",
  portalEngagementDesc: "Verified operating metrics from Lifewood's global AI data delivery network.",
  portalEthicsTitle: "Data Ethics & Compliance",
  portalEthicsDesc: "Your data is handled with the highest standards of security, privacy, and ethical responsibility.",
  portalPricingTitle: "Pricing Overview",
  portalPricingDesc: "Transparent, scalable models for every stage.",
  portalIndicativeRange: "Indicative Range",
  portalGetQuote: "Get a Custom Quote",
  portalPricingNote: "* All pricing is indicative. Final quotes are provided after a scoping call and are tailored to your project's specific requirements.",
  portalSendAnotherInquiry: "Send another inquiry",
  portalAccountDetails: "Account Details",
  portalProjectSpecifics: "Project Specifics",
  portalOutcomeExpectations: "Outcome Expectations",
  portalSelectService: "Select service",
  portalSelectModel: "Select model",
  portalServiceOption1: "Global Workforce Solutions",
  portalServiceOption2: "Custom AI Integration",
  portalServiceOption3: "Data Annotation",
  portalServiceOther: "Other",
  portalProcessStep1Title: "Initial Consultation & Scoping",
  portalProcessStep1Desc: "We discuss your goals, data needs, and project parameters.",
  portalProcessStep2Title: "Data Strategy & Planning",
  portalProcessStep2Desc: "We define the data architecture, guidelines, and success metrics.",
  portalProcessStep3Title: "AI Training & Data Pipeline",
  portalProcessStep3Desc: "Our expert teams annotate, label, and process your data.",
  portalProcessStep4Title: "Quality Assurance & Review",
  portalProcessStep4Desc: "Rigorous multi-tier QA ensures 99.9% accuracy.",
  portalProcessStep5Title: "Delivery & Integration",
  portalProcessStep5Desc: "Final datasets are delivered via API or secure transfer.",
  portalProcessStep6Title: "Post-Project Support",
  portalProcessStep6Desc: "Ongoing maintenance, feedback loops, and model retraining.",
  portalTools1Title: "AI & Machine Learning",
  portalTools1Desc: "Leveraging LLMs, computer vision models, and advanced NLP frameworks to accelerate data processing.",
  portalTools2Title: "Data Infrastructure",
  portalTools2Desc: "Secure, scalable cloud environments on AWS, GCP, and Azure with robust data lakes and pipelines.",
  portalTools3Title: "Annotation & QA Tools",
  portalTools3Desc: "Proprietary annotation platforms with built-in quality control systems for pixel-perfect accuracy.",
  portalTools4Title: "Delivery & Integration",
  portalTools4Desc: "Seamless API integrations, custom dashboards, and client-side connectors for real-time access.",
  portalToolsTagLLM: "LLMs",
  portalToolsTagCV: "Computer Vision",
  portalToolsTagNLP: "NLP",
  portalToolsTagAWS: "AWS",
  portalToolsTagGCP: "GCP",
  portalToolsTagAzure: "Azure",
  portalToolsTagLakes: "Data Lakes",
  portalToolsTagAnnot: "Annotation Platform",
  portalToolsTagQC: "QC Systems",
  portalToolsTagAPI: "APIs",
  portalToolsTagDash: "Dashboards",
  portalToolsTagConn: "Connectors",
  portalResultCard1Title: "Global Delivery Footprint",
  portalResultCard2Title: "Multilingual Data Capability",
  portalResultCard3Title: "Long-Run Enterprise Execution",
  portalEngage1Desc: "56,788 online resources operating across 30+ countries and 40+ delivery centers.",
  portalEngage1Use: "Built for large-scale AI data production with always-on global delivery coverage.",
  portalEngage2Desc: "50+ language capabilities and dialect support across multilingual data programs.",
  portalEngage2Use: "Helps teams ship culturally grounded, market-ready datasets for global AI models.",
  portalEngage3Desc: "Founded in 2005, with 20+ years of enterprise AI data operations experience.",
  portalEngage3Use: "Sustains long-duration programs with secure, process-driven execution at scale.",
  portalEthics1Title: "Data Privacy",
  portalEthics1Desc: "GDPR compliance, data minimization principles, and strict client data isolation to ensure sovereignty.",
  portalEthics2Title: "Security Protocols",
  portalEthics2Desc: "End-to-end encryption, role-based access controls, and secure data transfer mechanisms.",
  portalEthics3Title: "Ethical AI Practices",
  portalEthics3Desc: "Active bias mitigation, responsible annotation guidelines, and fair labor standards for our global workforce.",
  portalEthics4Title: "NDAs & Confidentiality",
  portalEthics4Desc: "Standardized NDA process, clear IP ownership, and anonymized outputs to protect your proprietary intelligence.",
  portalPricingTier1Title: "Starter",
  portalPricingTier1Desc: "Best for small, defined projects.",
  portalPricingTier1F1: "Up to 2 data types",
  portalPricingTier1F2: "Basic QA",
  portalPricingTier1F3: "Single delivery round",
  portalPricingTier2Title: "Growth",
  portalPricingTier2Desc: "Best for mid-scale or phased projects.",
  portalPricingTier2F1: "Multiple data types",
  portalPricingTier2F2: "Advanced QA",
  portalPricingTier2F3: "2 revision rounds",
  portalPricingTier2F4: "Dedicated PM",
  portalPricingTier3Title: "Enterprise",
  portalPricingTier3Range: "Custom Pricing",
  portalPricingTier3Desc: "For large-scale or retainer engagements.",
  portalPricingTier3F1: "Full pipeline management",
  portalPricingTier3F2: "Priority support",
  portalPricingTier3F3: "Ongoing delivery",
  portalPricingTier3F4: "Custom SLAs",
  portalRoadmap1Title: "Discovery Call",
  portalRoadmap1Desc: "We learn about your goals, data needs, and project scope in a 30-minute intro call.",
  portalRoadmap2Title: "Proposal & Scoping",
  portalRoadmap2Desc: "We send a tailored proposal outlining deliverables, timeline, and team structure.",
  portalRoadmap3Title: "Agreement & Onboarding",
  portalRoadmap3Desc: "Contracts are signed, NDAs established, and your dedicated team is assembled.",
  portalRoadmap4Title: "Project Kickoff",
  portalRoadmap4Desc: "Data pipelines are set up, workflows are defined, and work officially begins.",
  portalRoadmap5Title: "Delivery & Review",
  portalRoadmap5Desc: "Outputs are delivered in your preferred format with a review and feedback round.",
  portalRoadmap6Title: "Post-Project Support",
  portalRoadmap6Desc: "Ongoing support, iteration, or retainer engagement begins if needed.",
  portalContactTitle: "Corporate Inquiry",
  portalContactDesc: "Connect with our executive team for strategic partnerships and large-scale AI data initiatives.",
  impactTag: "Making a Difference",
  impactTitle: "Empowering Global Communities",
  impactSubtitle: "Our commitment to sustainable digital growth and ethical data stewardship.",
  impact1Title: "Digital Inclusion",
  impact1Text: "We bring high-tech employment opportunities to developing regions, fostering local talent and technical literacy.",
  impact2Title: "Gender Equality",
  impact2Text: "Proudly maintaining over 50% female leadership and workforce participation across our global delivery centers.",
  impact3Title: "Ethical AI Infrastructure",
  impact3Text: "We ensure every data point is handled with the highest standards of privacy and human dignity.",
  impactEsgDesc: "Lifewood is committed to building a digital future that is inclusive, diverse, and environmentally responsible. We measure our success not just by data points processed, but by lives improved.",
  impactChildLabor: "Child Labor Policy",
  impactFairWage: "Fair Wage Certified",
  impactWorkforcePart: "Global Workforce Participation",
  pSrv1Title: "Multimodal AI Labeling",
  pSrv1D1: "Semantic Segmentation",
  pSrv1D2: "3D Point Cloud",
  pSrv1D3: "LiDAR Annotation",
  pSrv1D4: "Multi-Object Tracking",
  pSrv2Title: "Generative AI RLHF",
  pSrv2D1: "Human Feedback",
  pSrv2D2: "Instruction Tuning",
  pSrv2D3: "Toxicity Moderation",
  pSrv2D4: "Reasoning Audits",
  pSrv3Title: "Multilingual Intelligence",
  pSrv3D1: "60+ Dialects",
  pSrv3D2: "Native Context",
  pSrv3D3: "Phonetic Audits",
  pSrv3D4: "Cultural Localization",
  pSrv4Title: "Medical Data Precision",
  pSrv4D1: "Radiology Masking",
  pSrv4D2: "Clinical Coding",
  pSrv4D3: "DICOM Labeling",
  pSrv4D4: "Scribe Support",
  pStepHeroTitle: "The Lifewood Onboarding.",
  pStepDiagnostic: "Diagnostic Phase",
  pStepDiagnosticDesc: "Technical audit of data silos and labeling requirements.",
  pStepInstructional: "Instructional PoC",
  pStepInstructionalDesc: "Iterative pilot with senior data engineers to refine SLAs.",
  pStepDeployment: "Secure Deployment",
  pStepDeploymentDesc: "Setting up biometric delivery centers and encrypted pipelines.",
  pStepScaling: "Dynamic Scaling",
  pStepScalingDesc: "Deploying 24/7 global resources for peak production output.",
  pStepTransitionTitle: "Rapid Deployment",
  pStepTransitionDesc: "From initial consultation to full active delivery center deployment.",
  pHist1Title: "Inception",
  pHist1Desc: "Founding of Lifewood with a focus on data quality.",
  pHist2Title: "Regional Expansion",
  pHist2Desc: "Opening of our massive Philippines delivery hub.",
  pHist3Title: "AI Pivot",
  pHist3Desc: "Integration of LLMs into our data processing pipelines.",
  pHist4Title: "Super-Bridge",
  pHist4Desc: "Launching the most secure 56K-strong talent network.",
  pContHQ: "Malaysia HQ",
  pContHQAddr: "Level 12, Tower A, PJ 33, Petaling Jaya",
  pContSales: "Enterprise Sales",
  pContSalesEmail: "exec-partnerships@lifewood.com",
  pContFormName: "Full Name",
  pContFormNamePlaceholder: "Your full name",
  pContFormEmail: "Work Email",
  pContFormEmailPlaceholder: "email@company.com",
  pContFormOrg: "Organization",
  pContFormOrgPlaceholder: "Company Name",
  pContFormMsg: "Tell us about your AI project scope",
  pContFormMsgPlaceholder: "Scope and requirements...",
  pContFormMsgDivided: "Interested? Discuss it with us.",
  pContFormBtn: "Submit Request",
  inquirySuccessTitle: "Inquiry Received",
  inquirySuccessMessage: "Thank you for reaching out. Your inquiry has been successfully sent to our executive team. We are currently reviewing your request and will get back to you within 24-48 business hours.",
  projHeroTitle: "Let's Get Started",
  projHeroDesc: "Tell Us About Your Project",
  projTimeline: "Timeline",
  projTimelineVal: "1-2 Business Days",
  projDeliverable: "Deliverable",
  projDeliverableVal: "Project Blueprint",
  projSecurityTitle: "Enterprise-Grade Security",
  projSecurityDesc: "We adhere to ISO 27001 standards and GDPR compliance. Your data remains isolated and encrypted throughout the entire lifecycle.",
  projReadyDeploy: "Ready for immediate deployment across 30+ countries.",
  projCtaTitle: "Start Your Project With Us Today",
  projCtaDesc: "Connect with our strategic solution architects to discuss your specific data needs.",
  projBtnExpert: "Talk to an Expert",
  projBtnEmail: "Email Us Directly",
  projFormRole: "Role / Job Title",
  projFormService: "Service of Interest",
  projFormBudget: "Budget Range (Optional)",
  projFormTimeline: "Desired Start Date",
  projFormSource: "How did you hear about us?",
  projFormNote: "Our team will reach out within 2 business days",
  projFormBudget1: "< $10k",
  projFormBudget2: "$10k - $50k",
  projFormBudget3: "$50k - $200k",
  projFormBudget4: "$200k+",
  projFormEngagement: "Preferred Engagement Model",
  projFormEng1: "Dedicated Team",
  projFormEng2: "One-time Project",
  projFormEng3: "Ongoing Retainer",
  projFormDataVolume: "Data Volume / Scale",
  projFormTechStack: "Current Tech Stack / Tools",
  projFormPriority: "Project Priority Level",
  projFormPrio1: "Urgent",
  projFormPrio2: "Planned",
  projFormPrio3: "Exploratory",
  projFormDecisionMaker: "Decision Maker Status",
  projFormDM1: "Final Decision Maker",
  projFormDM2: "Team Lead / Recommender",
  projFormDM3: "Other Consultant",
  projFormSuccess: "What does success look like to you?",
  projFormSuccessPlaceholder: "Describe your ideal project outcome...",
  projFormPreviousWork: "Have you worked with an AI data company before?",
  expHeroTag: "Enterprise AI Solutions",
  expHeroTitle: "Our Comprehensive Data Services",
  expHeroDesc: "We provide high-quality, at-scale human-in-the-loop data services that empower the world's most advanced AI models.",
  expSrv1Title: "Speech & Audio",
  expSrv1D1: "Phonetic Transcription",
  expSrv1D2: "Speaker Diarization",
  expSrv1D3: "Speech-to-Text Labeling",
  expSrv1D4: "Emotional Tone Analysis",
  expSrv1D5: "Wake-Word Collection",
  expSrv2Title: "Computer Vision",
  expSrv2D1: "2D/3D Bounding Boxes",
  expSrv2D2: "Semantic Segmentation",
  expSrv2D3: "Keypoint Annotation",
  expSrv2D4: "OCR & Text Extraction",
  expSrv2D5: "Facial Landmark Mapping",
  expSrv3Title: "Natural Language",
  expSrv3D1: "Entity Recognition (NER)",
  expSrv3D2: "Sentiment & Intent Tagging",
  expSrv3D3: "Multilingual Translation",
  expSrv3D4: "Content Summarization",
  expSrv3D5: "Search Query Relevance",
  landingSrv1Value: "Turn speech and audio into model-ready intelligence that improves product experience and automation outcomes.",
  landingSrv2Value: "Transform visual data into high-quality insights that help teams launch safer, smarter AI products faster.",
  landingSrv3Value: "Convert language data into reliable context so AI can understand users more accurately across markets.",
  landingServicesCta: "See Full Services",
  expCtaTitle: "Ready to build the future of AI?",
  expBtnReturn: "Return to Home",
  expBtnInquiry: "Send an Inquiry",
  careerCultureTitle: "Our AI Culture",
  careerCultureDesc: "We are a decentralized network of visionaries. Working at Lifewood means shaping the models that will define the next century.",
  careerJobsEngineering: "Engineering & Data Science",
  careerJobsOps: "Operations & Management",
  careerJobsSupport: "Global Support Services",
  careerBenefitRemote: "Remote & Hybrid First",
  careerBenefitRemoteDesc: "Work from any of our 40 delivery centers or from home.",
  careerBenefitDev: "Lifewood Academy",
  careerBenefitDevDesc: "Stipends for continuous learning in AI and Data Science.",
  careerBenefitHealth: "Global Wellness",
  careerBenefitHealthDesc: "Comprehensive health plans that follow you wherever you go.",
  careerHiringStep1: "Application Review",
  careerHiringStep1Desc: "Your application will be reviewed by our HR team.",
  careerHiringStep2: "CV Evaluation",
  careerHiringStep2Desc: "Your CV will be evaluated based on our requirements.",
  careerHiringStep3: "Confirmation",
  careerHiringStep3Desc: "You'll receive a confirmation email with your application details.",
  careerHiringStep4: "Team Contact",
  careerHiringStep4Desc: "Our team will contact you if your profile matches our needs.",
  careerValuesTitle: "Diversity & Inclusion",
  careerValuesDesc: "With resources in 30+ countries, diversity isn't a policy—it's our foundation. We celebrate the cultural nuances that make data human.",
  careerHeroTitle: "The Human Algorithm Needs You.",
  careerPulseNations: "Nations",
  careerPulseDialects: "Dialects",
  careerPulseSync: "Global Sync",
  careerVerifiedBadge: "Verified Expert Contribution",
  careerTestimonial1: "As an intern at Lifewood Data Technology, I have learned a lot about real-world AI data operations, teamwork, and professional responsibility. I gained hands-on experience in web development, production planning, and research, while improving my problem-solving and communication skills. This experience helped me grow both technically and personally.",
  careerTestimonial1Author: "Twinky Casidsid",
  careerTestimonial1Meta: "Batch 8 Lifewood Cebu Intern, 2026",
  careerJoinEliteTitle: "Join the Elite",
  careerJoinEliteDesc: "Be part of the 56K+ global experts defining AI integrity. We are scaling fast.",
  careerPerksTitle: "Perks of the Super-Bridge",
  careerNextTitle: "What Happens Next?",
  careerOpenPositionsTitle: "Open Positions",
  careerOpenPositionsDesc: "Shaping the future of machine learning across 30+ nations.",
  careerActiveRoles: "Active Roles",
  careerCompensationLabel: "Compensation",
  careerQualificationsBtn: "Qualifications",
  careerKeyQualifications: "Key Qualifications",
  careerApplyTitle: "Ready to make an impact?",
  careerApplyDesc: "Select a role and start your journey.",
  careerApplyNow: "Apply Now",
  careerCompensation: "Competitive & Merit-Based",
  careerJobTag: "Active Role",
  careerJob1Title: "Senior AI Data Architect",
  careerJob1Dept: "Engineering",
  careerJob1Loc: "Remote / Global",
  careerJob1Type: "Full-time",
  careerJob1Qual1: "5+ years experience in data architecture",
  careerJob1Qual2: "Proficiency in Python, SQL, and cloud platforms",
  careerJob1Qual3: "Experience with large-scale AI datasets",
  careerJob2Title: "Multilingual NLP Specialist",
  careerJob2Dept: "Data Science",
  careerJob2Loc: "Kuala Lumpur, MY",
  careerJob2Type: "Full-time",
  careerJob2Qual1: "Fluency in 3+ languages",
  careerJob2Qual2: "Background in Linguistics or Computational Linguistics",
  careerJob2Qual3: "Experience with NLP tools and frameworks",
  careerJob3Title: "AI Data Intern",
  careerJob3Dept: "Data Science",
  careerJob3Loc: "Global / Hybrid",
  careerJob3Type: "Internship",
  careerJob3Qual1: "Currently pursuing a degree in CS, Data Science, or related field",
  careerJob3Qual2: "Basic understanding of machine learning concepts",
  careerJob3Qual3: "Strong analytical skills",
  careerJob4Title: "Global Operations Manager",
  careerJob4Dept: "Operations",
  careerJob4Loc: "Manila, PH",
  careerJob4Type: "Full-time",
  careerJob4Qual1: "7+ years in operations management",
  careerJob4Qual2: "Experience leading cross-functional global teams",
  careerJob4Qual3: "Strong strategic planning abilities",
  careerJob5Title: "AI Training Associate",
  careerJob5Dept: "Quality Assurance",
  careerJob5Loc: "Hybrid / Global",
  careerJob5Type: "Contract",
  careerJob5Qual1: "Attention to detail",
  careerJob5Qual2: "Ability to follow complex guidelines",
  careerJob5Qual3: "Previous experience in data annotation is a plus",
  imgAltLifewoodLegacy: "Lifewood legacy",
  imgAltLifewoodTeam: "Lifewood team",
  imgAltProfilePerson: "Profile person",
  imgAltExpert: "Expert",
  imgAltTeamMember: "Team member",
  imgAltEsgTeam: "ESG team",
  ariaNextImage: "Next image",
  contactLandingHeader: "Have a question? Reach out.",
  contactLandingSub: "We'd love to hear from you. Our team typically responds within 24 hours.",
  contactSubjectLabel: "Inquiry Type",
  contactSubject1: "General Inquiry",
  contactSubject2: "Partnership",
  contactSubject3: "Media",
  contactSubject4: "Support",
  contactBtn: "Send Message",
  sendAnotherMessage: "Send another message",
  contactGeneralEmail: "contact@lifewood.com",
  contactMessagePlaceholder: "How can we help?",
  contactConnectWithUs: "Connect with us",
  contactConnectWithTeam: "Connect with our team",
  serviceDeepDiveOutcome: "Deep Dive / Outcome"
};

const zhBase: TranslationSet = {
  ...enBase,
  navAbout: "关于我们",
  navLegacy: "我们的传承",
  navOffices: "办公地点",
  navServices: "全球合作",
  navServicesOffered: "提供服务",
  navImpact: "社会影响",
  navCareers: "职业生涯",
  navJoinTeam: "加入我们",
  navContact: "联系我们",
  heroTitle: "全球领先的",
  heroHighlight: "人工智能驱动",
  heroTitleEnd: "数据解决方案提供商",
  heroSubtitle: "全天候服务，永不停歇",
  heroDescription: "我们助力企业释放 AI 的变革力量——赋予大数据生命，为人类福祉开启思考、学习和行动的新篇章。",
  heroBtnPrimary: "预约咨询",
  heroBtnSecondary: "探索服务",
  heroBtnTertiary: "Lifewood 门户",
  cardGlobalTitle: "全球版图",
  cardGlobalText: "遍布全球 30 多个国家的 40 多个交付中心",
  cardSpeedTitle: "速度与规模",
  cardSpeedText: "56,000 多名全球资源蓄势待发",
  cardPrecisionTitle: "精准度",
  cardPrecisionText: "支持 50 多种语言和方言",
  statCenters: "全球交付中心",
  statCountries: "业务覆盖国家",
  statLanguages: "语言支持能力",
  statResources: "全球人力资源",
  featuresTag: "我们的方法",
  featuresTitle: "通过创新跨越东西方",
  featuresDescription: "总部位于马来西亚，办公室战略性分布于各大洲，我们作为连接多元文化、技术和可能性的超级桥梁。",
  feature1Title: "灵活创新",
  feature1Text: "利用 GPT 和 Gemini 等前沿 AI 技术，打造随需求演进的变革性解决方案。",
  feature2Title: "全球协作",
  feature2Text: "将本地专业知识与全球 AI 基础设施相结合，赋能社区并推动全球包容性增长。",
  feature3Title: "技术驱动",
  feature3Text: "以前所未有的规模和速度部署先进的数据处理能力，解决现实世界的问题。",
  feature4Title: "致力于 ESG",
  feature4Text: "强调环境、社会和治理原则，包括就业多样性和社区赋能。",
  feature5Title: "始终可靠",
  feature5Text: "全天候提供一致的高质量结果，服务于全球最大的组织。",
  feature6Title: "有目的的影响",
  feature6Text: "致力于促进各地区的积极变革，创造机会，推动可持续的社会进步。",
  bgTag: "我们的传承",
  bgTitle: "超级桥梁的传奇",
  bgDesc: "Lifewood 成立于 2005 年，源于连接人类背景与机器智能的愿景。二十年来， we have evolved from a specialized data boutique into a global powerhouse.",
  portalNavContact: "与我们一起启动您的项目",
  servicesTag: "协作与项目",
  servicesTitle: "我们的全球投资组合",
  servicesDescription: "为全球最先进的 AI 模型提供动力的战略伙伴关系和高影响力的数据工程项目。",
  formSuccessTitle: "申请已收到",
  formSuccess: "感谢您的申请！我们的团队将审核您的资料，并在 5-7 个工作日内与您联系。",
  formSuccessExplore: "探索更多",
  formSuccessBack: "返回首页"
};

const msBase: TranslationSet = {
  ...enBase,
  navAbout: "Tentang Kami",
  navLegacy: "Warisan Kami",
  navOffices: "Pejabat Kami",
  navServices: "Kolaborasi",
  navServicesOffered: "Perkhidmatan Kami",
  navImpact: "Impak Kami",
  navCareers: "Kerjaya",
  navJoinTeam: "Sertai Kami",
  navContact: "Hubungi Kami",
  heroTitle: "Peneraju dunia dalam",
  heroHighlight: "Dikuasakan AI",
  heroTitleEnd: "penyelesaian data",
  heroSubtitle: "Sentiasa Hidup, Tidak Pernah Mati",
  heroDescription: "Kami memperkasakan organisasi untuk merealisasikan kuasa transformatif AI—menghidupkan data besar, melancarkan cara pemikiran baru for kebaikan manusia.",
  heroBtnPrimary: "Mohon Perundingan",
  heroBtnSecondary: "Teroka Perkhidmatan",
  heroBtnTertiary: "Portal Lifewood",
  cardGlobalTitle: "Jangkauan Global",
  cardGlobalText: "40+ pusat penghantaran di 30+ negara di seluruh dunia",
  cardSpeedTitle: "Kelajuan & Skala",
  cardSpeedText: "56,000+ sumber global sedia for digunakan",
  cardPrecisionTitle: "Ketepatan",
  cardPrecisionText: "50+ bahasa and dialek disokong",
  statCenters: "Pusat Penghantaran Global",
  statCountries: "Negara Seluruh Dunia",
  statLanguages: "Kemampuan Bahasa",
  statResources: "Sumber Global",
  featuresTag: "Pendekatan Kami",
  featuresTitle: "Merapatkan Timur & Barat Melalui Inovasi",
  featuresDescription: "Dengan ibu pejabat di Malaysia and pejabat strategik di seluruh benua, kami bertindak sebagai jambatan super yang menghubungkan kepelbagaian budaya, teknologi, och kemungkinan.",
  feature1Title: "Boleh Suai & Inovatif",
  feature1Text: "Kami memanfaatkan teknologi AI terkini termasuk GPT and Gemini for mencipta penyelesaian transformatif yang berkembang mengikut keperluan anda.",
  feature2Title: "Global Collaboration",
  feature2Text: "Menghubungkan kepakaran tempatan with infrastruktur AI global for memperkasakan komuniti och memacu pertumbuhan inklusif di seluruh dunia.",
  portalNavContact: "Mulakan Projek Anda Bersama Kami",
  formSuccessTitle: "Permohonan Diterima",
  formSuccess: "Terima kasih atas permohonan anda! Pasukan kami akan menyemak profil anda och menghubungi anda dalam masa 5-7 hari bekerja.",
  formSuccessExplore: "Teroka Lagi",
  formSuccessBack: "Kembali ke Laman Utama"
};

const tlBase: TranslationSet = {
  ...enBase,
  navAbout: "Tungkol sa Amin",
  navLegacy: "Ang Aming Pamana",
  navOffices: "Mga Opisina",
  navServices: "Mga Pakikipagtulungan",
  navServicesOffered: "Mga Serbisyo",
  navImpact: "Aming Impak",
  navCareers: "Mga Karera",
  navJoinTeam: "Sumali sa Amin",
  navContact: "Makipag-ugnayan",
  heroTitle: "Ang nangunguna sa mundo",
  heroHighlight: "Pinapatakbo ng AI",
  heroTitleEnd: "data solutions provider",
  heroSubtitle: "Laging Bukas, Hindi Nagsasara",
  heroDescription: "Binibigyang-kapangyarihan namin ang mga organisasyon na mapagtanto ang kapangyarihan ng AI para sa ikabubuti ng lahat.",
  heroBtnPrimary: "Mag-request ng Konsultasyon",
  heroBtnSecondary: "Galugarin ang Mga Serbisyo",
  heroBtnTertiary: "Lifewood Portal",
  cardGlobalTitle: "Global na Abot",
  cardGlobalText: "40+ delivery centers sa 30+ bansa sa buong mundo",
  cardSpeedTitle: "Bilis at Scale",
  cardSpeedText: "56,000+ pandaigdigang resources na handang i-deploy",
  cardPrecisionTitle: "Katumpakan",
  cardPrecisionText: "50+ na wika at dialekto ang suportado",
  featuresTag: "Aming Pamamaraan",
  featuresTitle: "Pag-uugnay sa Silangan at Kanluran sa pamamagitan ng Inobasyon",
  featuresDescription: "May headquarters sa Malaysia at mga tanggapang matatagpuan sa iba't ibang kontinente, nagsisilbi kaming super-bridge na nag-uugnay sa iba't ibang kultura at teknolohiya.",
  feature1Title: "Madaling Umangkop at Makabago",
  feature1Text: "Ginagamit namin ang makabagong teknolohiya ng AI kabilang ang GPT and Gemini para sa mga solusyong nagbabago ayon sa iyong pangangailangan.",
  portalNavHome: "Home",
  portalNavOffers: "Mga Tool",
  portalNavProcess: "Proseso Namin",
  portalNavResults: "Pakikipag-ugnayan",
  portalNavEthics: "Etika ng Datos",
  portalNavPricing: "Pagpepresyo",
  portalNavContact: "Simulan ang Iyong Proyekto Sa Amin",
  portalNavExit: "Lumabas sa Portal",
  portalHeroTitle: "Maligayang pagdating sa Lifewood Client Portal",
  portalHeroDesc: "Lahat ng kailangan mong malaman kung paano kami magtrabaho, anong gamit namin, at paano magsimula.",
  portalProcessTitle: "Aming Proseso",
  portalProcessDesc: "Subok na workflow para sa precision at scale.",
  portalOffersTitle: "Mga Tool at Teknolohiya",
  portalOffersDesc: "Pinapagana ng makabagong imprastraktura.",
  portalEngagementTitle: "Napatunayang Mga Resulta",
  portalEngagementDesc: "Mga beripikadong sukatan mula sa global AI data delivery network ng Lifewood.",
  portalEthicsTitle: "Etika at Pagsunod sa Datos",
  portalEthicsDesc: "Hinahawakan ang iyong datos sa pinakamataas na pamantayan ng seguridad, privacy, at etikal na responsibilidad.",
  portalPricingTitle: "Pangkalahatang Presyo",
  portalPricingDesc: "Transparent at scalable na modelo sa bawat yugto.",
  portalIndicativeRange: "Indicative Range",
  portalGetQuote: "Humingi ng Custom Quote",
  portalPricingNote: "* Indicative lamang ang lahat ng presyo. Ibinibigay ang final quote pagkatapos ng scoping call at iniayon sa pangangailangan ng proyekto.",
  portalSendAnotherInquiry: "Magpadala ng panibagong inquiry",
  portalAccountDetails: "Detalye ng Account",
  portalProjectSpecifics: "Detalye ng Proyekto",
  portalOutcomeExpectations: "Inaasahang Resulta",
  portalSelectService: "Pumili ng serbisyo",
  portalSelectModel: "Pumili ng model",
  portalServiceOption1: "Global Workforce Solutions",
  portalServiceOption2: "Custom AI Integration",
  portalServiceOption3: "Data Annotation",
  portalServiceOther: "Iba pa",
  portalProcessStep1Title: "Unang Konsultasyon at Scoping",
  portalProcessStep1Desc: "Pinag-uusapan natin ang iyong goals, data needs, at project parameters.",
  portalProcessStep2Title: "Data Strategy at Planning",
  portalProcessStep2Desc: "Tinutukoy namin ang data architecture, guidelines, at success metrics.",
  portalProcessStep3Title: "AI Training at Data Pipeline",
  portalProcessStep3Desc: "Ina-annotate, nilalabel, at pinoproseso ng aming expert teams ang iyong data.",
  portalProcessStep4Title: "Quality Assurance at Review",
  portalProcessStep4Desc: "Mahigpit na multi-tier QA para sa 99.9% accuracy.",
  portalProcessStep5Title: "Delivery at Integration",
  portalProcessStep5Desc: "Ang final datasets ay dina-deliver sa API o secure transfer.",
  portalProcessStep6Title: "Post-Project Support",
  portalProcessStep6Desc: "Patuloy na maintenance, feedback loops, at model retraining.",
  portalEngage1Desc: "56,788 online resources na kumikilos sa 30+ bansa at 40+ delivery centers.",
  portalEngage1Use: "Dinisenyo para sa malakihang AI data production na may always-on global delivery.",
  portalEngage2Desc: "50+ language capabilities at dialect support para sa multilingual data programs.",
  portalEngage2Use: "Tumutulong maghatid ng culturally grounded at market-ready datasets para sa global AI models.",
  portalEngage3Desc: "Itinatag noong 2005, na may 20+ taong karanasan sa enterprise AI data operations.",
  portalEngage3Use: "Pinananatili ang pangmatagalang programa gamit ang secure at process-driven execution sa scale.",
  portalEthics1Title: "Privacy ng Datos",
  portalEthics1Desc: "GDPR compliance, data minimization, at mahigpit na data isolation para sa data sovereignty.",
  portalEthics2Title: "Security Protocols",
  portalEthics2Desc: "End-to-end encryption, role-based access controls, at secure data transfer mechanisms.",
  portalEthics3Title: "Etikal na AI Practices",
  portalEthics3Desc: "Bias mitigation, responsableng annotation guidelines, at patas na labor standards.",
  portalEthics4Title: "NDA at Kumpidensiyalidad",
  portalEthics4Desc: "Standardized NDA process, malinaw na IP ownership, at anonymized outputs.",
  portalPricingTier1Title: "Starter",
  portalPricingTier1Desc: "Mainam para sa maliit at defined na proyekto.",
  portalPricingTier1F1: "Hanggang 2 data types",
  portalPricingTier1F2: "Basic QA",
  portalPricingTier1F3: "Isang delivery round",
  portalPricingTier2Title: "Growth",
  portalPricingTier2Desc: "Mainam para sa mid-scale o phased na proyekto.",
  portalPricingTier2F1: "Maramihang data types",
  portalPricingTier2F2: "Advanced QA",
  portalPricingTier2F3: "2 revision rounds",
  portalPricingTier2F4: "Dedicated PM",
  portalPricingTier3Title: "Enterprise",
  portalPricingTier3Range: "Custom Pricing",
  portalPricingTier3Desc: "Para sa large-scale o retainer engagements.",
  portalPricingTier3F1: "Full pipeline management",
  portalPricingTier3F2: "Priority support",
  portalPricingTier3F3: "Ongoing delivery",
  portalPricingTier3F4: "Custom SLAs",
  portalRoadmap1Title: "Discovery Call",
  portalRoadmap1Desc: "Inaalam namin ang goals, data needs, at scope sa 30-minute intro call.",
  portalRoadmap2Title: "Proposal at Scoping",
  portalRoadmap2Desc: "Nagpapadala kami ng tailored proposal para sa deliverables, timeline, at team.",
  portalRoadmap3Title: "Kasunduan at Onboarding",
  portalRoadmap3Desc: "Pinipirmahan ang kontrata, inaayos ang NDA, at binubuo ang dedicated team.",
  portalRoadmap4Title: "Project Kickoff",
  portalRoadmap4Desc: "Ina-setup ang data pipelines, workflows, at opisyal na pagsisimula ng trabaho.",
  portalRoadmap5Title: "Delivery at Review",
  portalRoadmap5Desc: "Dina-deliver ang outputs sa preferred format kasama ang review at feedback round.",
  portalRoadmap6Title: "Post-Project Support",
  portalRoadmap6Desc: "Patuloy na suporta, iteration, o retainer engagement kung kinakailangan.",
  contactConnectWithUs: "Kumonekta sa amin",
  contactConnectWithTeam: "Kumonekta sa aming team",
  serviceDeepDiveOutcome: "Mas Malalim na Pagsusuri / Kinalabasan",
  bgTag: "Ang Aming Pamana",
  bgTitle: "Ang Pamana ng Super-Bridge",
  bgDesc: "Itinatag noong 2005, isinilang ang Lifewood mula sa bisyong pagdugtungin ang konteksto ng tao at katalinuhan ng makina. Sa loob ng dalawang dekada, lumago kami mula sa isang specialized data boutique tungo sa isang global powerhouse.",
  bgPoint1Title: "20 Taon ng Kahusayan",
  bgPoint1Text: "Dalawang dekada ng pagpino sa metodolohiyang 'Human-in-the-Loop'.",
  bgPoint2Title: "Kultural na Katalinuhan",
  bgPoint2Text: "Malalim na pag-unawa sa mahigit 60 wika at diyalekto upang maging mas may konteksto at walang pagkiling ang AI.",
  bgPoint3Title: "Ang Pamantayan ng Lifewood",
  bgPoint3Text: "Pagtatakda ng pandaigdigang pamantayan sa seguridad ng datos gamit ang air-gapped centers at biometric protocols.",
  bgYearsBadge: "Taon ng Estratehikong AI Data Engineering",
  officesTitle: "Pandaigdigang Estratehikong Presensya",
  officesDesc: "May mga specialized delivery center at secure business hub kami sa mahahalagang technology corridor sa buong mundo.",
  officesAlwaysOn: "Laging Bukas • Hindi Nagsasara • Pandaigdigang Saklaw",
  officesRealtime: "Real-time na delivery na aktibo sa lahat ng time zone",
  portalNavContact: "Simulan ang Iyong Project Kasama Kami",
  formSuccessTitle: "Natanggap ang Aplikasyon",
  formSuccess: "Salamat sa iyong aplikasyon! Susuriin ng aming koponan ang iyong pagsusumite at makikipag-ugnayan sa loob ng 5-7 araw.",
  formSuccessExplore: "Mag-explore Pa",
  formSuccessBack: "Bumalik sa Home"
};

const bnBase: TranslationSet = {
  ...enBase,
  navAbout: "আমাদের সম্পর্কে",
  navLegacy: "আমাদের ঐতিহ্য",
  navOffices: "অফিসসমূহ",
  navServices: "সহযোগিতা",
  navServicesOffered: "প্রদত্ত সেবা",
  navImpact: "আমাদের প্রভাব",
  navCareers: "ক্যারিয়ার",
  navJoinTeam: "আমাদের সাথে যোগ দিন",
  navContact: "যোগাযোগ করুন",
  heroTitle: "বিশ্বের শীর্ষস্থানীয়",
  heroHighlight: "AI-চালিত",
  heroTitleEnd: "ডেটা সলিউশন প্রোভাইডার",
  heroSubtitle: "সর্বদা চালু, কখনও বন্ধ নয়",
  heroDescription: "আমরা সংস্থাগুলোকে AI-এর রূপান্তরমূলক শক্তি উপলব্ধি করতে সক্ষম করি—মানবজাতির মঙ্গলের জন্য বড় ডেটাকে জীবন্ত করে তুলি।",
  heroBtnPrimary: "পরামর্শের জন্য অনুরোধ করুন",
  heroBtnSecondary: "সার্ভিসগুলো দেখুন",
  heroBtnTertiary: "লাইফউড পোর্টাল",
  cardGlobalTitle: "বৈশ্বিক বিস্তৃতি",
  cardGlobalText: "৩০টিরও বেশি দেশে ৪০টিরও বেশি ডেলিভারি সেন্টার",
  cardSpeedTitle: "গতি এবং স্কেল",
  cardSpeedText: "৫৬,০০০+ বৈশ্বিক রিসোর্স ব্যবহারের জন্য প্রস্তুত",
  cardPrecisionTitle: "নির্ভুলতা",
  cardPrecisionText: "৫০টিরও বেশি ভাষা ও উপভাষা সমর্থিত",
  featuresTag: "আমাদের পদ্ধতি",
  featuresTitle: "উদ্ভাবনের মাধ্যমে পূর্ব ও পশ্চিমের মধ্যে সেতুবন্ধন",
  featuresDescription: "মালয়েশিয়ায় সদর দপ্তর এবং বিভিন্ন মহাদেশে কৌশলগতভাবে অবস্থিত অফিসের মাধ্যমে আমরা বৈচিত্র্যময় সংস্কৃতি ও প্রযুক্তিকে সংযুক্ত করি।",
  portalNavContact: "আমাদের সাথে আপনার প্রজেক্ট শুরু করুন",
  formSuccessTitle: "আবেদন জমা হয়েছে",
  formSuccess: "আপনার আবেদনের জন্য ধন্যবাদ! আমাদের টিম আপনার প্রোফাইল পর্যালোচনা করবে এবং ৫-৭ কার্যদিবসের মধ্যে আপনার সাথে যোগাযোগ করবে।",
  formSuccessExplore: "আরও জানুন",
  formSuccessBack: "হোমপেজে ফিরে যান"
};

const hiBase: TranslationSet = {
  ...enBase,
  navAbout: "हमारे बारे में",
  navLegacy: "हमारी विरासत",
  navOffices: "हमारे कार्यालय",
  navServices: "सहयोग",
  navServicesOffered: "प्रदत्त सेवाएं",
  navImpact: "हमारा प्रभाव",
  navCareers: "करियर",
  navJoinTeam: "हमसे जुड़ें",
  navContact: "संपर्क करें",
  heroTitle: "दुनिया का अग्रणी",
  heroHighlight: "AI-संचालित",
  heroTitleEnd: "डेटा समाधान प्रदाता",
  heroSubtitle: "हमेशा चालू, कभी बंद नहीं",
  heroDescription: "हम संगठनों को AI की परिवर्तनकारी शक्ति का एहसास कराने के लिए सशक्त बनाते हैं—मानवता की भलाई के लिए डेटा को जीवंत करते हैं।",
  heroBtnPrimary: "परामर्श का अनुरोध करें",
  heroBtnSecondary: "सेवाओं का अन्वेषण करें",
  heroBtnTertiary: "लाइफवुड पोर्टल",
  cardGlobalTitle: "वैश्विक पहुंच",
  cardGlobalText: "दुनिया भर के 30+ देशों में 40+ डिलीवरी केंद्र",
  cardSpeedTitle: "गति and पैमाना",
  cardSpeedText: "56,000+ वैश्विक संसाधन तैनात करने के लिए तैयार",
  cardPrecisionTitle: "सटीकता",
  cardPrecisionText: "50+ भाषाओं and बोलियों का समर्थन",
  portalNavContact: "हमारे साथ अपना प्रोजेक्ट शुरू करें",
  formSuccessTitle: "आवेदन प्राप्त हुआ",
  formSuccess: "आपके आवेदन के लिए धन्यवाद! हमारी टीम आपकी प्रोफाइल की समीक्षा करेगी and 5-7 कार्य दिवसों में आपसे संपर्क करेगी।",
  formSuccessExplore: "और अधिक जानें",
  formSuccessBack: "होम पेज पर वापस जाएं"
};

const esBase: TranslationSet = {
  ...enBase,
  navAbout: "Sobre Nosotros",
  navLegacy: "Nuestro Legado",
  navOffices: "Oficinas",
  navServices: "Colaboraciones",
  navServicesOffered: "Servicios Ofrecidos",
  navImpact: "Impacto",
  navCareers: "Carreras",
  navJoinTeam: "Únete al Equipo",
  navContact: "Contacto",
  heroTitle: "Líder mundial en",
  heroHighlight: "IA-impulsada",
  heroTitleEnd: "soluciones de datos",
  heroSubtitle: "Siempre activo, nunca apagado",
  heroDescription: "Empoderamos a las organizaciones para que realicen el power transformador de la IA, dando vida a los macrodatos.",
  heroBtnPrimary: "Solicitar una Consulta",
  heroBtnSecondary: "Ver Servicios",
  heroBtnTertiary: "Portal Lifewood",
  cardGlobalTitle: "Alcance Global",
  cardGlobalText: "Más de 40 centros en más de 30 países",
  cardSpeedTitle: "Velocidad y Escala",
  cardSpeedText: "Más de 56,000 recursos globales listos para desplegar",
  cardPrecisionTitle: "Precisión",
  cardPrecisionText: "Soporte para más de 50 idiomas and dialectos",
  portalNavContact: "Inicia tu Proyecto con Nosotros",
  formSuccessTitle: "Solicitud Recibida",
  formSuccess: "¡Gracias por tu solicitud! Nuestro equipo revisará tu perfil and te contactará en 5-7 días hábiles.",
  formSuccessExplore: "Explorar más",
  formSuccessBack: "Volver al Inicio"
};

const jaBase: TranslationSet = {
  ...enBase,
  navAbout: "会社概要",
  navLegacy: "私たちの歩み",
  navOffices: "オフィス",
  navServices: "グローバル連携",
  navServicesOffered: "提供サービス",
  navImpact: "社会的インパクト",
  navCareers: "採用情報",
  navJoinTeam: "チームに参加する",
  navContact: "お問い合わせ",
  heroTitle: "世界をリードする",
  heroHighlight: "AI駆動型",
  heroTitleEnd: "データソリューション",
  heroSubtitle: "常時稼働、決して止まらない",
  heroDescription: "私たちは、AI의 変革力を活用してビッグデータを活性化させ、人類의 進歩のために新たな思考と学習의 道を開きます。",
  heroBtnPrimary: "コンサルティングを依頼する",
  heroBtnSecondary: "サービスを探索する",
  heroBtnTertiary: "Lifewoodポータル",
  cardGlobalTitle: "グローバル展開",
  cardGlobalText: "世界30カ国以上に40以上의 デリバリーセンター",
  cardSpeedTitle: "スピードと規模",
  cardSpeedText: "56,000人以上의 グローバルリソースが展開可能",
  cardPrecisionTitle: "精度",
  cardPrecisionText: "50以上의 言語と方言をサポート",
  portalNavContact: "私たちと一緒にプロジェクトを開始する",
  formSuccessTitle: "応募を受け付けました",
  formSuccess: "ご応募ありがとうございます。採用担当者が内容を確認し、5〜7営業日以内にご連絡いたします。",
  formSuccessExplore: "さらに詳しく",
  formSuccessBack: "ホームに戻る"
};

const koBase: TranslationSet = {
  ...enBase,
  navAbout: "회사 소개",
  navLegacy: "우리의 유산",
  navOffices: "글로벌 사무소",
  navServices: "글로벌 협업",
  navServicesOffered: "제공 서비스",
  navImpact: "사회적 영향",
  navCareers: "채용 정보",
  navJoinTeam: "인재 채용",
  navContact: "고객 문의",
  heroTitle: "세계를 선도하는",
  heroHighlight: "AI 기반",
  heroTitleEnd: "데이터 솔루션 기업",
  heroSubtitle: "언제나 켜져 있고, 결코 꺼지지 않는",
  heroDescription: "우리는 기업들이 AI의 변혁적인 힘을 실현할 수 있도록 돕고, 인류의 발전을 위해 데이터를 생생하게 구현합니다.",
  heroBtnPrimary: "컨설팅 요청하기",
  heroBtnSecondary: "서비스 둘러보기",
  heroBtnTertiary: "Lifewood 포털",
  cardGlobalTitle: "글로벌 네트워크",
  cardGlobalText: "전 세계 30개국 이상에 40개 이상 의 센터 보유",
  cardSpeedTitle: "속도 및 규모",
  cardSpeedText: "56,000명 이상의 글로벌 인력 즉시 투입 가능",
  cardPrecisionTitle: "정밀도",
  cardPrecisionText: "50개 이상의 언어 및 방언 지원",
  portalNavContact: "우리와 함께 프로젝트 시작하기",
  formSuccessTitle: "지원서 접수 완료",
  formSuccess: "지원해 주셔서 감사합니다! 검토 후 5-7 영업일 이내에 연락드리겠습니다.",
  formSuccessExplore: "더 알아보기",
  formSuccessBack: "홈으로 돌아가기"
};

export const TRANSLATIONS: Translations = {
  en: enBase,
  zh: zhBase,
  ms: msBase,
  tl: tlBase,
  bn: bnBase,
  hi: hiBase,
  es: esBase,
  ja: jaBase,
  ko: koBase
};
