const fs = require("fs");

const path = "constants.ts";
let src = fs.readFileSync(path, "utf8");

const bases = [
  "enBase",
  "zhBase",
  "msBase",
  "tlBase",
  "bnBase",
  "hiBase",
  "esBase",
  "jaBase",
  "koBase",
];

const localeByBase = {
  enBase: "en",
  zhBase: "zh",
  msBase: "ms",
  tlBase: "tl",
  bnBase: "bn",
  hiBase: "hi",
  esBase: "es",
  jaBase: "ja",
  koBase: "ko",
};

const t = {
  modalSubtitle: {
    en: "Be part of the world's leading AI-powered data solutions provider",
    zh: "加入全球领先的 AI 数据解决方案团队",
    ms: "Sertai peneraju global penyelesaian data berkuasa AI",
    tl: "Maging bahagi ng nangungunang AI-powered data solutions team sa mundo",
    bn: "বিশ্বের শীর্ষস্থানীয় AI-চালিত ডেটা সলিউশন টিমের অংশ হন",
    hi: "दुनिया के अग्रणी AI-संचालित डेटा सॉल्यूशंस प्रदाता का हिस्सा बनें",
    es: "Forma parte del proveedor líder mundial de soluciones de datos impulsadas por IA",
    ja: "世界をリードするAIデータソリューション企業の一員になりませんか",
    ko: "세계 최고 수준의 AI 기반 데이터 솔루션 팀에 합류하세요",
  },
  expHeroDesc: {
    en: "We provide high-quality, at-scale human-in-the-loop data services that empower the world's most advanced AI models.",
    zh: "我们提供高质量、可规模化的 human-in-the-loop 数据服务，赋能全球最先进的 AI 模型。",
    ms: "Kami menyediakan perkhidmatan data human-in-the-loop berkualiti tinggi pada skala besar untuk memperkasa model AI paling maju di dunia.",
    tl: "Nagbibigay kami ng de-kalidad at at-scale na human-in-the-loop data services para mapalakas ang pinaka-advanced na AI models sa mundo.",
    bn: "আমরা উচ্চমানের, বৃহৎ-স্কেলের human-in-the-loop ডেটা সেবা প্রদান করি, যা বিশ্বের সবচেয়ে উন্নত AI মডেলগুলোকে সক্ষম করে।",
    hi: "हम उच्च-गुणवत्ता, बड़े पैमाने की human-in-the-loop डेटा सेवाएं प्रदान करते हैं, जो दुनिया के सबसे उन्नत AI मॉडलों को सक्षम बनाती हैं।",
    es: "Brindamos servicios de datos human-in-the-loop de alta calidad y a escala para potenciar los modelos de IA más avanzados del mundo.",
    ja: "世界最先端のAIモデルを支える、高品質かつ大規模なHuman-in-the-Loopデータサービスを提供しています。",
    ko: "세계에서 가장 진보한 AI 모델을 지원하는 고품질·대규모 human-in-the-loop 데이터 서비스를 제공합니다.",
  },
  footerCopyright: {
    en: "Lifewood Data Technology. All Rights Reserved.",
    zh: "Lifewood Data Technology。保留所有权利。",
    ms: "Lifewood Data Technology. Hak cipta terpelihara.",
    tl: "Lifewood Data Technology. Lahat ng karapatan ay nakalaan.",
    bn: "Lifewood Data Technology। সর্বস্বত্ব সংরক্ষিত।",
    hi: "Lifewood Data Technology। सर्वाधिकार सुरक्षित।",
    es: "Lifewood Data Technology. Todos los derechos reservados.",
    ja: "Lifewood Data Technology。無断転載を禁じます。",
    ko: "Lifewood Data Technology. All rights reserved.",
  },
  careerTestimonial1Meta: {
    en: "Batch 8 Lifewood Cebu Intern, 2026",
    zh: "Lifewood Cebu 实习生第8期，2026",
    ms: "Intern Lifewood Cebu Kumpulan 8, 2026",
    tl: "Batch 8 Lifewood Cebu Intern, 2026",
    bn: "Lifewood Cebu ইন্টার্ন, ব্যাচ ৮, ২০২৬",
    hi: "Lifewood Cebu इंटर्न बैच 8, 2026",
    es: "Pasantía Lifewood Cebu, Cohorte 8, 2026",
    ja: "Lifewood Cebu インターン 第8期, 2026",
    ko: "Lifewood Cebu 인턴 8기, 2026",
  },

  formPhoneCodeMY: {
    en: "Malaysia (+60)",
    zh: "马来西亚 (+60)",
    ms: "Malaysia (+60)",
    tl: "Malaysia (+60)",
    bn: "মালয়েশিয়া (+60)",
    hi: "मलेशिया (+60)",
    es: "Malasia (+60)",
    ja: "マレーシア (+60)",
    ko: "말레이시아 (+60)",
  },
  formPhoneCodePH: {
    en: "Philippines (+63)",
    zh: "菲律宾 (+63)",
    ms: "Filipina (+63)",
    tl: "Pilipinas (+63)",
    bn: "ফিলিপাইন (+63)",
    hi: "फिलीपींस (+63)",
    es: "Filipinas (+63)",
    ja: "フィリピン (+63)",
    ko: "필리핀 (+63)",
  },
  formPhoneCodeCN: {
    en: "China (+86)",
    zh: "中国 (+86)",
    ms: "China (+86)",
    tl: "China (+86)",
    bn: "চীন (+86)",
    hi: "चीन (+86)",
    es: "China (+86)",
    ja: "中国 (+86)",
    ko: "중국 (+86)",
  },
  formPhoneCodeJP: {
    en: "Japan (+81)",
    zh: "日本 (+81)",
    ms: "Jepun (+81)",
    tl: "Japan (+81)",
    bn: "জাপান (+81)",
    hi: "जापान (+81)",
    es: "Japón (+81)",
    ja: "日本 (+81)",
    ko: "일본 (+81)",
  },
  formPhoneCodeGB: {
    en: "United Kingdom (+44)",
    zh: "英国 (+44)",
    ms: "United Kingdom (+44)",
    tl: "United Kingdom (+44)",
    bn: "যুক্তরাজ্য (+44)",
    hi: "यूनाइटेड किंगडम (+44)",
    es: "Reino Unido (+44)",
    ja: "英国 (+44)",
    ko: "영국 (+44)",
  },
  formPhoneCodeUS: {
    en: "United States (+1)",
    zh: "美国 (+1)",
    ms: "Amerika Syarikat (+1)",
    tl: "United States (+1)",
    bn: "যুক্তরাষ্ট্র (+1)",
    hi: "संयुक्त राज्य (+1)",
    es: "Estados Unidos (+1)",
    ja: "米国 (+1)",
    ko: "미국 (+1)",
  },
  formPhoneCodeTW: {
    en: "Taiwan (+886)",
    zh: "中国台湾 (+886)",
    ms: "Taiwan (+886)",
    tl: "Taiwan (+886)",
    bn: "তাইওয়ান (+886)",
    hi: "ताइवान (+886)",
    es: "Taiwán (+886)",
    ja: "台湾 (+886)",
    ko: "대만 (+886)",
  },

  officeCityPetalingJaya: {
    en: "Petaling Jaya",
    zh: "八打灵再也",
    ms: "Petaling Jaya",
    tl: "Petaling Jaya",
    bn: "পেতালিং জায়া",
    hi: "पेतालिंग जाया",
    es: "Petaling Jaya",
    ja: "ペタリンジャヤ",
    ko: "페탈링자야",
  },
  officeCityManila: {
    en: "Manila",
    zh: "马尼拉",
    ms: "Manila",
    tl: "Maynila",
    bn: "ম্যানিলা",
    hi: "मनीला",
    es: "Manila",
    ja: "マニラ",
    ko: "마닐라",
  },
  officeCityDavao: {
    en: "Davao",
    zh: "达沃",
    ms: "Davao",
    tl: "Davao",
    bn: "দাভাও",
    hi: "दावाओ",
    es: "Dávao",
    ja: "ダバオ",
    ko: "다바오",
  },
  officeCityCebu: {
    en: "Cebu",
    zh: "宿务",
    ms: "Cebu",
    tl: "Cebu",
    bn: "সেবু",
    hi: "सेबू",
    es: "Cebú",
    ja: "セブ",
    ko: "세부",
  },
  officeCityShenzhen: {
    en: "Shenzhen",
    zh: "深圳",
    ms: "Shenzhen",
    tl: "Shenzhen",
    bn: "শেনঝেন",
    hi: "शेन्ज़ेन",
    es: "Shenzhen",
    ja: "深セン",
    ko: "선전",
  },
  officeCityTokyo: {
    en: "Tokyo",
    zh: "东京",
    ms: "Tokyo",
    tl: "Tokyo",
    bn: "টোকিও",
    hi: "टोक्यो",
    es: "Tokio",
    ja: "東京",
    ko: "도쿄",
  },
  officeCityLondon: {
    en: "London",
    zh: "伦敦",
    ms: "London",
    tl: "London",
    bn: "লন্ডন",
    hi: "लंदन",
    es: "Londres",
    ja: "ロンドン",
    ko: "런던",
  },
  officeCityNewYork: {
    en: "New York",
    zh: "纽约",
    ms: "New York",
    tl: "New York",
    bn: "নিউ ইয়র্ক",
    hi: "न्यूयॉर्क",
    es: "Nueva York",
    ja: "ニューヨーク",
    ko: "뉴욕",
  },
  officeCityTaipei: {
    en: "Taipei",
    zh: "台北",
    ms: "Taipei",
    tl: "Taipei",
    bn: "তাইপেই",
    hi: "ताइपेई",
    es: "Taipéi",
    ja: "台北",
    ko: "타이베이",
  },

  officeCountryMalaysia: {
    en: "Malaysia",
    zh: "马来西亚",
    ms: "Malaysia",
    tl: "Malaysia",
    bn: "মালয়েশিয়া",
    hi: "मलेशिया",
    es: "Malasia",
    ja: "マレーシア",
    ko: "말레이시아",
  },
  officeCountryPhilippines: {
    en: "Philippines",
    zh: "菲律宾",
    ms: "Filipina",
    tl: "Pilipinas",
    bn: "ফিলিপাইন",
    hi: "फिलीपींस",
    es: "Filipinas",
    ja: "フィリピン",
    ko: "필리핀",
  },
  officeCountryChina: {
    en: "China",
    zh: "中国",
    ms: "China",
    tl: "China",
    bn: "চীন",
    hi: "चीन",
    es: "China",
    ja: "中国",
    ko: "중국",
  },
  officeCountryJapan: {
    en: "Japan",
    zh: "日本",
    ms: "Jepun",
    tl: "Japan",
    bn: "জাপান",
    hi: "जापान",
    es: "Japón",
    ja: "日本",
    ko: "일본",
  },
  officeCountryUnitedKingdom: {
    en: "United Kingdom",
    zh: "英国",
    ms: "United Kingdom",
    tl: "United Kingdom",
    bn: "যুক্তরাজ্য",
    hi: "यूनाइटेड किंगडम",
    es: "Reino Unido",
    ja: "英国",
    ko: "영국",
  },
  officeCountryUnitedStates: {
    en: "United States",
    zh: "美国",
    ms: "Amerika Syarikat",
    tl: "United States",
    bn: "যুক্তরাষ্ট্র",
    hi: "संयुक्त राज्य",
    es: "Estados Unidos",
    ja: "米国",
    ko: "미국",
  },
  officeCountryTaiwan: {
    en: "Taiwan",
    zh: "中国台湾",
    ms: "Taiwan",
    tl: "Taiwan",
    bn: "তাইওয়ান",
    hi: "ताइवान",
    es: "Taiwán",
    ja: "台湾",
    ko: "대만",
  },

  officeAddressPetalingJaya: {
    en: "B-13-01, Menara Bata, PJ Trade Centre, No 8, Jalan PJU 8/8A, Bandar Damansara Perdana, 47820 Petaling Jaya, Selangor",
    zh: "马来西亚雪兰莪州八打灵再也 47820，B-13-01，Menara Bata，PJ Trade Centre，No 8，Jalan PJU 8/8A，Bandar Damansara Perdana",
    ms: "B-13-01, Menara Bata, PJ Trade Centre, No 8, Jalan PJU 8/8A, Bandar Damansara Perdana, 47820 Petaling Jaya, Selangor",
    tl: "B-13-01, Menara Bata, PJ Trade Centre, No 8, Jalan PJU 8/8A, Bandar Damansara Perdana, 47820 Petaling Jaya, Selangor",
    bn: "B-13-01, Menara Bata, PJ Trade Centre, No 8, Jalan PJU 8/8A, Bandar Damansara Perdana, 47820 Petaling Jaya, Selangor",
    hi: "B-13-01, Menara Bata, PJ Trade Centre, No 8, Jalan PJU 8/8A, Bandar Damansara Perdana, 47820 Petaling Jaya, Selangor",
    es: "B-13-01, Menara Bata, PJ Trade Centre, No 8, Jalan PJU 8/8A, Bandar Damansara Perdana, 47820 Petaling Jaya, Selangor",
    ja: "B-13-01、Menara Bata、PJ Trade Centre、No 8, Jalan PJU 8/8A、Bandar Damansara Perdana、47820 ペタリンジャヤ、セランゴール",
    ko: "B-13-01, Menara Bata, PJ Trade Centre, No 8, Jalan PJU 8/8A, Bandar Damansara Perdana, 47820 Petaling Jaya, Selangor",
  },
  officeAddressManila: {
    en: "26th Street, Bonifacio Global City, Taguig, Metro Manila",
    zh: "菲律宾大马尼拉大区塔吉格市，Bonifacio Global City，26th Street",
    ms: "26th Street, Bonifacio Global City, Taguig, Metro Manila",
    tl: "26th Street, Bonifacio Global City, Taguig, Metro Manila",
    bn: "26th Street, Bonifacio Global City, Taguig, Metro Manila",
    hi: "26th Street, Bonifacio Global City, Taguig, Metro Manila",
    es: "26th Street, Bonifacio Global City, Taguig, Metro Manila",
    ja: "26th Street、Bonifacio Global City、Taguig、Metro Manila",
    ko: "26th Street, Bonifacio Global City, Taguig, Metro Manila",
  },
  officeAddressDavao: {
    en: "Pryce Tower, Bajada, Davao City",
    zh: "菲律宾达沃市 Bajada，Pryce Tower",
    ms: "Pryce Tower, Bajada, Davao City",
    tl: "Pryce Tower, Bajada, Davao City",
    bn: "Pryce Tower, Bajada, Davao City",
    hi: "Pryce Tower, Bajada, Davao City",
    es: "Pryce Tower, Bajada, Dávao",
    ja: "Pryce Tower、Bajada、Davao City",
    ko: "Pryce Tower, Bajada, Davao City",
  },
  officeAddressCebu: {
    en: "Cebu IT Park, Lahug, Cebu City",
    zh: "菲律宾宿务市 Lahug，Cebu IT Park",
    ms: "Cebu IT Park, Lahug, Cebu City",
    tl: "Cebu IT Park, Lahug, Cebu City",
    bn: "Cebu IT Park, Lahug, Cebu City",
    hi: "Cebu IT Park, Lahug, Cebu City",
    es: "Cebu IT Park, Lahug, Cebú",
    ja: "Cebu IT Park、Lahug、Cebu City",
    ko: "Cebu IT Park, Lahug, Cebu City",
  },
  officeAddressShenzhen: {
    en: "Nanshan Science and Technology Park, Nanshan District",
    zh: "中国深圳市南山区，南山科技园",
    ms: "Nanshan Science and Technology Park, Nanshan District",
    tl: "Nanshan Science and Technology Park, Nanshan District",
    bn: "Nanshan Science and Technology Park, Nanshan District",
    hi: "Nanshan Science and Technology Park, Nanshan District",
    es: "Nanshan Science and Technology Park, Distrito de Nanshan",
    ja: "南山サイエンス＆テクノロジーパーク、南山区",
    ko: "Nanshan Science and Technology Park, Nanshan District",
  },
  officeAddressTokyo: {
    en: "Marunouchi, Chiyoda City, Tokyo",
    zh: "日本东京千代田区丸之内",
    ms: "Marunouchi, Chiyoda City, Tokyo",
    tl: "Marunouchi, Chiyoda City, Tokyo",
    bn: "Marunouchi, Chiyoda City, Tokyo",
    hi: "Marunouchi, Chiyoda City, Tokyo",
    es: "Marunouchi, Chiyoda, Tokio",
    ja: "東京都千代田区丸の内",
    ko: "Marunouchi, Chiyoda City, Tokyo",
  },
  officeAddressLondon: {
    en: "Canary Wharf, London",
    zh: "英国伦敦金丝雀码头",
    ms: "Canary Wharf, London",
    tl: "Canary Wharf, London",
    bn: "Canary Wharf, London",
    hi: "Canary Wharf, London",
    es: "Canary Wharf, Londres",
    ja: "ロンドン、カナリー・ワーフ",
    ko: "Canary Wharf, London",
  },
  officeAddressNewYork: {
    en: "Manhattan Business District, New York, NY",
    zh: "美国纽约州纽约市，曼哈顿商务区",
    ms: "Manhattan Business District, New York, NY",
    tl: "Manhattan Business District, New York, NY",
    bn: "Manhattan Business District, New York, NY",
    hi: "Manhattan Business District, New York, NY",
    es: "Distrito Empresarial de Manhattan, Nueva York, NY",
    ja: "ニューヨーク州ニューヨーク、マンハッタン・ビジネス地区",
    ko: "Manhattan Business District, New York, NY",
  },
  officeAddressTaipei: {
    en: "Xinyi District, Taipei City",
    zh: "中国台湾台北市信义区",
    ms: "Xinyi District, Taipei City",
    tl: "Xinyi District, Taipei City",
    bn: "Xinyi District, Taipei City",
    hi: "Xinyi District, Taipei City",
    es: "Distrito de Xinyi, Taipéi",
    ja: "台北市信義区",
    ko: "Xinyi District, Taipei City",
  },
};

function getBlockRange(baseName) {
  const start = src.indexOf(`const ${baseName}: TranslationSet = {`);
  if (start < 0) throw new Error(`Missing block ${baseName}`);
  const i = bases.indexOf(baseName);
  const next = bases[i + 1];
  const end = next
    ? src.indexOf(`const ${next}: TranslationSet = {`, start)
    : src.indexOf("export const TRANSLATIONS", start);
  if (end < 0) throw new Error(`Missing block end ${baseName}`);
  return { start, end };
}

for (const base of bases) {
  const locale = localeByBase[base];
  const { start, end } = getBlockRange(base);
  let block = src.slice(start, end);

  for (const [key, values] of Object.entries(t)) {
    const val = values[locale];
    if (!val) continue;
    const line = `  ${key}: ${JSON.stringify(val)},`;
    const rx = new RegExp(`^\\s{2}${key}:\\s*".*",?\\s*$`, "m");
    if (rx.test(block)) {
      block = block.replace(rx, line);
    } else {
      block = block.replace(/\n};\s*$/, `\n${line}\n};`);
    }
  }

  src = src.slice(0, start) + block + src.slice(end);
}

fs.writeFileSync(path, src, "utf8");
console.log("Updated translated keys across all locales.");
